name: Play DOOM in GitHub Actions
on: [workflow_dispatch]

jobs:
  doom:
    runs-on: ubuntu-latest
    steps:
      - name: Instalar DOOM (prboom)
        run: |
          sudo apt-get update
          sudo apt-get install -y prboom

      - name: Baixar arquivo WAD (DOOM 1)
        run: |
          wget https://github.com/msikma/doom-wads/raw/master/doom1.wad -O doom1.wad

      - name: Rodar DOOM (modo terminal)
        run: |
          echo "Use CTRL+C para sair."
          prboom -iwad doom1.wad -nomouse
